### ISSUE TITLE
"Corruption detected" on messages sent by Heka

### ISSUE THREAD

**Issue by PrFalken** [imgix/heka_exporter#1]
Here is my heka Output config : 
```
[MonitoringPrometheusOutput]
type = "UdpOutput"
message_matcher = "Type == 'MonitoringInput'"
encoder = "ProtobufEncoder"
address = "xxx.xxx.xxx.xxx:50569"}}"
```

Messages are sent via UDP to the exporter, but they all get rejected with the error : 
``` Corruption detected at bytes: xxx```

Apparently when calling : 
```
n, record, err := sr.GetRecordFromStream(listener)
```
record is always empty. the exporter calls : 
```
bytesRead = bytes.IndexByte(buf, message.RECORD_SEPARATOR)
```
and bytesRead is always -1.
does it mean I don't use the right encoder ? I get confused, as your code states that it should receive heka protobuf messages.

**Comment by davidbirdsong** [comment]
try adding: `use_framing = true` to your output config

example:
```toml
[MonitoringPrometheusOutput]
type = "UdpOutput"
message_matcher = "Type == 'MonitoringInput'"
encoder = "ProtobufEncoder"
address = "xxx.xxx.xxx.xxx:50569"
```
